package com.xiaopeng.ota.bean;
/* loaded from: classes2.dex */
public enum Action {
    SHOW_CAMPAIGN,
    START_INSTALL,
    ECU_VERSION_CHANGED,
    CLOSE,
    SCHEDULE,
    SCHEDULE_SUCCESS,
    CANCEL_USER_SCHEDULE,
    CLEAR_SCHEDULE,
    CANCEL_SCHEDULE_SUCCESS,
    CANCEL_UPGRADE,
    CANCEL_AUTO_SCHEDULE,
    AUTO_UPGRADE,
    AUTO_UPGRADE_DISABLED,
    GEARLEVER_CHANGED,
    INSTALL_EXIT,
    INSTALL_COMPLETED,
    CAMPAIGN_READY,
    CAMPAIGN_CANCEL,
    START_FRAGMENT,
    USB_PROGRESS,
    USB_FOLODER
}
